import type { Proposal } from './types'

export const data: Proposal[] = [
  {
    id: 'prop-1',
    vendor: 'TechCorp A.Ş.',
    rfpTitle: 'Akıllı Sayaç Donanım Alımı',
    amount: 4250000,
    currency: 'TRY',
    status: 'under-review',
    score: 94,
    technicalScore: 96,
    financialScore: 88,
    complianceScore: 98,
    riskLevel: 'low',
    deliveryTime: 90,
    warranty: 24,
  },
  {
    id: 'prop-2',
    vendor: 'SmartMeter Ltd.',
    rfpTitle: 'Akıllı Sayaç Donanım Alımı',
    amount: 4680000,
    currency: 'TRY',
    status: 'pending',
    score: 76,
    technicalScore: 82,
    financialScore: 65,
    complianceScore: 78,
    riskLevel: 'medium',
    deliveryTime: 120,
    warranty: 18,
  },
  {
    id: 'prop-3',
    vendor: 'Dijital Çözümler A.Ş.',
    rfpTitle: 'Akıllı Sayaç Donanım Alımı',
    amount: 3950000,
    currency: 'TRY',
    status: 'approved',
    score: 89,
    technicalScore: 91,
    financialScore: 95,
    complianceScore: 82,
    riskLevel: 'low',
    deliveryTime: 75,
    warranty: 36,
  },
  {
    id: 'prop-4',
    vendor: 'InnoTech Solutions',
    rfpTitle: 'Bulut Altyapı Migrasyonu',
    amount: 2850000,
    currency: 'TRY',
    status: 'under-review',
    score: 82,
    technicalScore: 88,
    financialScore: 78,
    complianceScore: 80,
    riskLevel: 'medium',
    deliveryTime: 60,
    warranty: 12,
  },
  {
    id: 'prop-5',
    vendor: 'MegaTech Enterprises',
    rfpTitle: 'Sayaç Kurulum Hizmetleri',
    amount: 1950000,
    currency: 'TRY',
    status: 'rejected',
    score: 58,
    technicalScore: 62,
    financialScore: 72,
    complianceScore: 40,
    riskLevel: 'high',
    deliveryTime: 180,
    warranty: 12,
  },
]
